### ISSUE TITLE
entriesClient.getEntryListing() does not deserialize properties of Shortcut

### ISSUE THREAD

**Issue by Ke-Jin-Laserfiche** [Laserfiche/lf-repository-api-client-js#46]
the API server response contains targetType and targetId
```{
    "id": 161761,
    "name": "2019 VitaFlex FSA New Hire Guidelines (3)",
    "parentId": 6461,
    "fullPath": "\\Integrations LB\\2019 VitaFlex FSA New Hire Guidelines (3)",
    "folderPath": "\\Integrations LB",
    "creator": "quinn.mchale@laserfiche.com",
    "creationTime": "2022-07-07T18:26:34Z",
    "lastModifiedTime": "2022-07-07T18:26:34Z",
    "entryType": "Shortcut",
    "templateId": 0,
    "rowNumber": 8,
    "targetType@odata.type": "#Laserfiche.Repository.EntryType",
    "targetType": "Document",
    "targetId": 156759,
    "extension": "pdf"
}
```
but the corresponding entry in the returned ODataValueContextOfIListOfEntry does not contain these properties.

**Comment by terrencejames-lf** [comment]
https://github.com/RicoSuter/NJsonSchema/wiki/Inheritance

To summarize: 

- API server needs to have this additional `JsonConverter(typeof(JsonInheritanceConverter)` attribute on top of declaring KnownTypes in order for inheritance to properly work, i.e. for the swagger.json to correctly map which types have a hierarchy
- We can then generate the new client library with this swagger.json
- It looks like the way this works, the API server will now send in an additional property "discriminator" to tell the client library which type to deserialize into, ex Shortcut, Folder, and Document for Entry. The library looks for this property when it receives the response from the server before constructing the object:
![image](https://user-images.githubusercontent.com/101907777/187495212-95d5ec5e-127f-4093-b79c-1e9e96fee768.png)
- The only issue is, we already have a property "entryType" that contains this info already. I'm seeing if we can just go off of that, but It seems like the swagger.json generation is sensitive so that I can't make the "discriminator" property a name that already is being used. I'm seeing if there's another workaround like using the liquid template. But if anything, we might just have to settle on having this additional property.
- This issue could imply that other client libraries are facing the same thing
- Currently also investigating if we have other types that behave like Entry
